### Test
GET http://localhost:3003/ping

### Create a new cliente
POST http://localhost:3003/client
Content-Type: application/json

{
    "name":"Allef Souza"
}

### Get All Clients
GET http://localhost:3003/allclients
Content-Type: application/json

### Get All Pizzas
GET http://localhost:3003/allpizzas
Content-Type: application/json

### Create Orders
POST http://localhost:3003/createorder
Content-Type: application/json

{
    "fk_client":1,
    "pizzas":[
  {
    "id": 1,
    "nome": "Portuguesa"
    
  },
  {
    "id": 2,
    "nome": "Napolitana"
    
  }
 
]
}

### Get All Prices
GET http://localhost:3003/allprices
Content-Type: application/json
