### Test
GET http://localhost:3003/ping

### Create a new cliente
POST http://localhost:3003/createClient
Content-Type: application/json

{
    "name": "Teste1",
    "phone": "123456789",
    "payment": "credito",
    "address": "Rua Teste",
    "number": "123"
}

### Create Orders
POST http://localhost:3003/createorder
Content-Type: application/json

{
  "id_cliente": 15,
  "pizzas": [10,20]
  
}

### Get All Clients
GET http://localhost:3003/allclients
Content-Type: application/json

### Get All Orders
GET http://localhost:3003/allorders
Content-Type: application/json

### Get All Pizzas
GET http://localhost:3003/allpizzas
Content-Type: application/json

### Get All Prices
GET http://localhost:3003/allprices
Content-Type: application/json

### Delete Client
DELETE http://localhost:3003/clients/4
Content-Type: application/json

### Delete Orders
DELETE http://localhost:3003/orders/2
Content-Type: application/json
